from abc import ABC, abstractmethod
import asyncio
from app.models.schemas import ChatResponse, ChartData, UnifiedResponse
from typing import Dict, Any, Optional

class AIBaseProvider(ABC):
    @abstractmethod
    async def generate_response(self, query: str, context: str) -> ChatResponse:
        pass

class MockAIProvider(AIBaseProvider):
    async def generate_response(self, query: str, context: str) -> ChatResponse:
        # Simulate realistic "AI thinking" time
        await asyncio.sleep(1)
        
        # Simple keyword matching to generate relevant mock data
        q_lower = query.lower()
        
        # Default Mock Response
        explanation = "This is a simulated AI response generated by the Mock Provider. The system is currently running in DEV_MODE or simulating a fallback scenario."
        insights = [
            "Mock Insight: Market volatility is simulated.",
            "Mock Insight: Data integrity checks passed.",
            "Mock Insight: Offline mode active."
        ]
        asset = None
        chart_data = None
        
        # Mocking specific asset queries
        if "bitcoin" in q_lower or "btc" in q_lower:
            asset = "bitcoin"
            explanation = "Bitcoin (Mock) is showing strong resistance at the $100k level. This is a simulated analysis based on mock data patterns."
            chart_data = ChartData(
                title="Bitcoin Price (Mock)",
                labels=["Jan", "Feb", "Mar", "Apr", "May"],
                values=[45000, 48000, 52000, 49000, 53000],
                x_label="Month",
                y_label="Price (USD)"
            )
        elif "ethereum" in q_lower or "eth" in q_lower:
            asset = "ethereum"
            explanation = "Ethereum (Mock) is transitioning to a new consensus validation phase in this simulation."
            chart_data = ChartData(
                title="Ethereum Price (Mock)",
                labels=["Jan", "Feb", "Mar", "Apr", "May"],
                values=[2800, 3100, 3000, 3400, 3600],
                x_label="Month",
                y_label="Price (USD)"
            )
            
        return ChatResponse(
            explanation=explanation,
            insights=insights,
            asset=asset,
            chart_data=chart_data
        )

    async def get_unified_response(self, query: str) -> UnifiedResponse:
        """
        Returns a complete UnifiedResponse for DEV_MODE orchestration.
        Bypasses Planner, Fetcher, and Analyzer.
        """
        # Call the existing generator to get the 'meat' of the response
        chat_resp = await self.generate_response(query, context="dev_mode")
        
        # Determine intent based on asset presence
        response_type = "market" if chat_resp.asset else "concept"
        
        # Mock Social Data
        mock_social = {
            "status": "High Activity",
            "score": 0.85,
            "volume_24h": 12500
        }
        
        # Mock News
        mock_news = [
            {"title": f"Breaking: {query.title()} Adoption Surges in Speculative Markets", "url": "#"},
            {"title": "Global Markets React to New Crypto Regulations", "url": "#"},
            {"title": "Tech Analysis: Key Support Levels Tested", "url": "#"}
        ]

        # Concept KPIs (for Concept mode)
        concept_kpis = []
        if response_type == "concept":
            concept_kpis = [
                {"label": "Category", "value": "Blockchain"},
                {"label": "Consensus", "value": "Proof-of-Stake"},
                {"label": "Origin", "value": "2015"}
            ]

        return UnifiedResponse(
            query=query,
            type=response_type,
            content=chat_resp.explanation,
            chat_summary="Mock simulation of market data.",
            chart_data=chat_resp.chart_data,
            insights=chat_resp.insights,
            concept_kpis=concept_kpis,
            social_sentiment=mock_social,
            news_headlines=mock_news,
            source_url="https://en.wikipedia.org/wiki/Simulated_Reality",
            asset=chat_resp.asset,
            is_error=False
        )
